name: out hello world!
on:
  push: 
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs: 
  say-hello-world:
    name: "say hello wolrd"
    runs-on: ubuntu-latest
    steps:
    - name: print hello world
      run: echo < ls
