name: out hello world!
workflow-dispatch:

jobs: 
  say-hello-world:
    name: "say hello wolrd"
    runs-on: ubuntu-latest
    steps:
    - name: print hello world
      run: echo "compiling...."